#!/bin/bash
cd ~
pwd
whoami
date
cd /var/restic
rm *.gz
echo mysql
mysql -e "show databases;" | sed -e 's/\|//g' -e 's/Database//g' -e '/^$/d' | awk '{print "/opt/restic/exportar " $1}' | bash
echo backblaze
/opt/restic/backblaze
